title: That Tech Support Guy
email: subah2subah@gmail.com
author: subah2subah
description: >- 
  I write about tech, poetry and life.
baseurl: "/blog" # the subpath of your site, e.g. /blog
#baseurl: ""
url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ""
github_username:  thattechsupportguy
rss: "Subscribe to rss"
permalink: /:categories/:title

links:
  - title: Poetry
    url: /poetry/
  - title: Technology
    url: /technology/
  - title: Product
    url: /product/
  - title: About
    url: /about/

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
    sass_dir: _sass  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
